[project]
name = "tinygent"
version = "0.1.0"
description = "Tiny agentic framework for building AI agents which can do more than tiny tasks."
readme = "README.md"
authors = [
    { name = "Filip Chytil", email = "chytilfilip@gmail.com" }
]
requires-python = "==3.12.*"
dependencies = [
    "async-lru>=2.0.5",
    "jinja2>=3.1.6",
    "langchain-core>=0.3.74",
    "openai>=1.101.0",
    "pydantic>=2.11.7",
    "pyyaml>=6.0.2",
]

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "mypy>=1.17.1",
    "ruff>=0.12.11",
]

[project.scripts]
lint = "scripts.lint:main"
fmt = "scripts.fmt:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["tinygent"]
