[project]
name = "tinygent"
version = "0.1.0"
description = "Tiny agentic framework for building AI agents which can do more than tiny tasks."
readme = "README.md"
authors = [
    { name = "Filip Chytil", email = "chytilfilip@gmail.com" }
]
requires-python = "==3.12.*"
dependencies = [
    "async-lru>=2.0.5",
    "langchain-core>=0.3.74",
    "openai>=1.101.0",
    "pydantic>=2.11.7",
]

[project.optional-dependencies]
dev = [
    "black>=25.1.0",
    "mypy>=1.17.1",
    "ruff>=0.12.11",
]

[project.scripts]
lint = "scripts.lint:main"
fmt = "scripts.fmt:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
package = true

[tool.hatch.build.targets.wheel]
packages = ["tinygent"]

[tool.black]
line-length = 89
target-version = ["py312"]
skip-string-normalization = true

[tool.mypy]
python_version = 3.12
files = ["tinygent", "scripts"]
ignore_missing_imports = true
disable_error_code = ["attr-defined"]

[tool.ruff]
target-version = "py312"
src = ["tinygent", "scripts"]
line-length = 89

[tool.ruff.format]
quote-style = "single"

[tool.ruff.lint]
extend-select = [
    "I",  # Import-related rules
]
ignore = [
    "E731",  # Do not complain about assignments to lambda expressions
]

[tool.ruff.lint.isort]
force-single-line = true
combine-as-imports = false
force-sort-within-sections = true
known-first-party = ["tinygent"]
