[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tiny-openai"
version = "0.1.0"
dependencies = [
    "langchain-core>=0.3.74",
    "openai>=1.101.0",
    "tinygent",
]

[project.entry-points.components]
tiny_openai = "tiny_openai.register"

[tool.hatch.build.targets.wheel]
packages = ["src/tiny_openai"]

[tool.uv.sources]
tinygent = { workspace = true }
