[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tiny-chat"
version = "0.1.0"
dependencies = [
    "tinygent",
]

[tool.hatch.build.targets.wheel]
packages = ["src/tiny_chat"]

[tool.uv.sources]
tinygent = { workspace = true }
