[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "tiny-chat"
version = "0.1.0"
dependencies = [
    "fastapi>=0.120.2",
    "pydantic>=2.11.7",
    "tinygent",
    "uvicorn[standard]>=0.38.0",
]

[tool.hatch.build]
include = [
    "src/tiny_chat/frontend/dist/**/*"
]

[tool.hatch.build.targets.wheel]
packages = ["src/tiny_chat"]

[tool.uv.sources]
tinygent = { workspace = true }
